version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run:
          name: "Install libman"
          command: dotnet tool install -g Microsoft.Web.LibraryManager.Cli
      - run:
          name: "Restore Client-Side libraries"
          command: |
            %userprofile%\.dotnet\tools\libman restore
          working_directory: App
      - run:
          name: "Restore App Packages"
          command: dotnet restore
          working_directory: App
      - run:
          name: "Install Entity Framework tool"
          command: dotnet tool install -g dotnet-ef
      - run:
          name: "Add Initial migration"
          command: |
            %userprofile%\.dotnet\tools\dotnet-ef migrations add InitialMigration
          working_directory: App
      - run:
          name: "Drop Database"
          command: |
            %userprofile%\.dotnet\tools\dotnet-ef database drop -f
          working_directory: App
      - run:
          name: "Update Database"
          command: |
            %userprofile%\.dotnet\tools\dotnet-ef database update
          working_directory: App
      - run:
          name: "Build"
          command: dotnet build -c Release
          working_directory: App
      - run:
          name: "Restore App.Tests Packages"
          command: dotnet restore
          working_directory: App.Tests
      - run:
          name: "Build Tests"
          command: dotnet build -c Release
          working_directory: App
      - run:
          name: "Run Tests"
          command: dotnet test
          working_directory: App.Tests
