name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install libman
      run: dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    - name: Restore Client-Side libraries
      run: libman restore
      working-directory: App
    - name: Restore dependencies
      run: dotnet restore
      working-directory: App
    - name: Build
      run: dotnet build -c Release
      working-directory: App
