name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install libman
      run: dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    - name: Restore Client-Side libraries
      run: libman restore
      working-directory: App
    - name: Restore dependencies
      run: dotnet restore
      working-directory: App
    - name: Install Entity Framework tool
      run: dotnet tool install -g dotnet-ef
    - name: Add Initial migration
      run: dotnet ef migrations add InitialMigration
      working-directory: App
    - name: Drop Database
      run: dotnet ef database drop -f
      working-directory: App
    - name: Update Database
      run: dotnet ef database update
      working-directory: App
    - name: Build
      run: dotnet build -c Release
      working-directory: App
    - name: Restore App.Tests Packages
      run: dotnet restore
      working-directory: App.Tests
    - name: Build Tests
      run: dotnet build -c Release
      working-directory: App.Tests
    - name: Run Tests
      run: dotnet test
      working-directory: App.Tests